// <auto-generated />
using System;
using BlogSpot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogSpot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903120000_AddPostScheduling")]
    partial class AddPostScheduling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Note: This is a partial designer file
            // The full snapshot has been updated in AppDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
